---
title: "Fiona Data"
author: "Jim Wright"
date: "2/12/2020"
output: html_document
toc: true
toc_float: true 
theme: united 
highlight: zenburn 
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE,
                      echo = FALSE,
                      dev.args = list(bg="transparent"))

library(tidyverse)
library(rio)
library(here)
library(colorblindr)
library(gghighlight)
library(forcats)
library(ggrepel)
library(distill)
library(knitr)
library(kableExtra)


diaper <- import(here("data", "fiona_diaper.sav"),
               setclass = "tbl_df") %>% 
               characterize() %>% 
               janitor::clean_names() 


feed <- import(here("data", "fiona_feed.sav"),
               setclass = "tbl_df") %>% 
               characterize() %>% 
               janitor::clean_names() 



```


```{r data explore, include=TRUE}
head(diaper)

head(feed)


mean_feed_duration <- feed %>% 
  summarize(mean(feeding_duration))

mean_feed_duration

mean_daily_feed <- feed %>% 
  summarize(mean(feeding))

mean_daily_feed

feed %>% 
  count(feeding)


mean_daily_change <- diaper %>% 
  summarize(mean(diaper_number))

mean_daily_change
  
```


```{r kable tables, include=TRUE}

feed_table_1 <- feed %>% 
  group_by(date, feeding, feeding_time, feeding_duration, source)

knitr::kable(feed_table_1, 
             caption = "Fiona Feeding Data",
             col.names = c("Date",
                           "Day Number",
                           "Feeding Number",
                           "Feeding Time",
                           "Feeding Duration",
                           "Source")) %>% 
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                 fixed_thead = TRUE) %>% 
   column_spec(1:6, bold = T, border_right = T, color = "black") %>% 
   row_spec(0, color = "black") 
 


diaper_table_1 <- diaper %>% 
  group_by(date, day, diaper_number, diaper_type, change_time)

knitr::kable(diaper_table_1, 
             caption = "Fiona Diaper Data",
             col.names = c("Date",
                           "Day Number",
                           "Diaper Number",
                           "Diaper Type",
                           "Change Time")) %>% 
   kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                 fixed_thead = TRUE) %>% 
   column_spec(1:5, bold = T, border_right = T, color = "black") %>% 
   row_spec(0, color = "black") 


```